# Draw Lines and Shape 

In [1]:
# import libraries 
import cv2 as cv 
import numpy as np 

1- Draw a Canvas

In [5]:
# import libraries 
import cv2 as cv 
import numpy as np 

# 1- draw a canvas   0 is for black 
img=np.zeros((600,600))

# ones is for white
img1=np.ones((600,600))

cv.imshow("Black Canvas", img)
cv.imshow("White canvas", img1)

cv.waitKey(0)
cv.destroyAllWindows()

2- Print the matix of Canvas

In [8]:
# import libraries 
import cv2 as cv 
import numpy as np 

# 1- draw a canvas   0 is for black 
img=np.zeros((600,600))

# 2- The size of a canvas
print("The size of our canvas is :", img.shape)
print("The actual Matrix", img)

cv.imshow("Black Canvas", img)
cv.waitKey(0)
cv.destroyAllWindows()

The size of our canvas is : (600, 600)
The actual Matrix [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


3- Adding colors to canvas

In [25]:
# import libraries 
import cv2 as cv 
import numpy as np 

# 1- draw a canvas   0 is for black 
img=np.zeros((600,600))

# 2- The size of a canvas
print("The size of our canvas is :", img.shape)

# adding colors
colored_img=np.zeros((600,600,3), np.uint8)  # 3 means three channels
colored_img[:]= 255,0,255                    # : complete image and = color key
colored_img[150:230, 100:207]=255,0,0        # colord the part of image 

# adding line
cv.line(colored_img, (0,0),(colored_img.shape[0],colored_img.shape[1]),(255,0,0), 3)  #crossed line
cv.line(colored_img, (20,20),(300,300),(255,255,50), 3)                               # part of lines 


cv.imshow("Black Canvas", img)
cv.imshow("Colored Image", colored_img)
cv.waitKey(0)
cv.destroyAllWindows()

The size of our canvas is : (600, 600)


4- Adding Rectangle  

In [55]:
# import libraries 
import cv2 as cv 
import numpy as np 

# 1- draw a canvas   0 is for wblack 
img=np.zeros((600,600))

# 2- The size of a canvas
print("The size of our canvas is :", img.shape)

# 3- adding rectangle 
cv.rectangle(img, (50,100),(300,400), (255,255,255),3)

# 4- fill the color in rectangle
# cv.rectangle(img, (50,100),(300,400), (255,255,255),100)  # increased the thickness or (we should used the below code)
cv.rectangle(img, (50,100),(300,400), (255,255,255), cv.FILLED)

# adding circle
cv.circle(img,(400,300),50,(255,100,0),5)

# filling the circle
cv.circle(img,(400,300),50,(255,100,0),cv.FILLED)



cv.imshow("Rectangle Added Image", img)
cv.waitKey(0)
cv.destroyAllWindows()

The size of our canvas is : (600, 600)


5- Adding text

In [57]:
# import libraries 
import cv2 as cv 
import numpy as np 

# 1- draw a canvas   0 is for wblack 
img=np.zeros((600,600))

# 2- The size of a canvas
print("The size of our canvas is :", img.shape)

# 3- adding text
cv.putText(img, "Python Learning By Muhammad Jamal", (200,500), cv.FONT_HERSHEY_COMPLEX, 1, (255,255,0), 2)
# Assignmet: how to bring the above text into two lines 

cv.imshow("Rectangle Added Image", img)
cv.waitKey(0)
cv.destroyAllWindows()

The size of our canvas is : (600, 600)
